version: '3'
services:
  api:
    image: node
    tty: true
    environment:
      - MYSQL_SERVER=db
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_DATABASE=${DB_NAME}
      - TZ=${TZ}
      - CHOKIDAR_USEPOLLING=true
    ports:
      - '3000:3000'
    volumes:
      - ./:/app
    working_dir: /app
    networks:
      backend:
        ipv4_address: 172.28.1.10

  # app:
  #   image: node

networks:
  backend:
    driver: bridge
    name: app_network
    ipam:
      config:
        - subnet: 172.28.1.0/24